"""Ícones em pixel art (12x12) para itens, atividades, botões e barras de status."""
import random
from functools import lru_cache

from PySide6.QtCore import Qt
from PySide6.QtGui import QColor, QImage, QPainter

from .. import cosmetics

_APPLE = [
    "......b.....",
    ".....bgg....",
    "..rrrbrrr...",
    ".rhhrrrrrr..",
    ".rhrrrrrrrR.",
    ".rrrrrrrrrR.",
    ".rrrrrrrrrR.",
    ".rrrrrrrrRR.",
    "..rrrrrrRR..",
    "..RrrrrRRR..",
    "...RR.RRR...",
    "............",
]

_BOTTLE = [
    ".....cc.....",
    ".....ww.....",
    "....w..w....",
    "....w..w....",
    "...w....w...",
    "..wLLLLLLw..",
    "..wLhLLLLw..",
    "..wLLLLLLw..",
    "..wLLLLLDw..",
    "...wLLLDw...",
    "....wwww....",
    "............",
]

ICONS: dict[str, tuple[list[str], dict[str, str]]] = {
    # ---- comidas ----
    "maca": (_APPLE, {"r": "#D32F2F", "R": "#8E1B1B", "h": "#FF8A80", "b": "#5D4037", "g": "#43A047"}),
    "maca_dourada": (_APPLE, {"r": "#FFCA28", "R": "#C79100", "h": "#FFF59D", "b": "#5D4037", "g": "#FFE082"}),
    "pao": ([
        "............",
        "............",
        ".......yyy..",
        ".....yyYYYy.",
        "...yyYYyYYYy",
        "..yYYyYYyYYd",
        ".yYYyYYyYYdd",
        "yYYyYYyYYdd.",
        "yYYYYYYYdd..",
        ".ddYYYYdd...",
        "..dddddd....",
        "............",
    ], {"y": "#E0A84F", "Y": "#C98A2E", "d": "#8B5A1E"}),
    "cenoura": ([
        ".........gg.",
        "........gGg.",
        ".......gGg..",
        "......ooG...",
        ".....oOo....",
        "....oOoo....",
        "...oooO.....",
        "..oOoo......",
        "..ooo.......",
        ".oo.........",
        ".o..........",
        "............",
    ], {"o": "#F57C00", "O": "#BF5000", "g": "#66BB6A", "G": "#2E7D32"}),
    "batata": ([
        "............",
        "............",
        "....dddd....",
        "..ddYyyYdd..",
        ".dYyyyyyYYd.",
        ".dyyYyyyyyd.",
        ".dyyyyyYyyd.",
        ".dYyyyyyyYd.",
        "..ddYyyYdd..",
        "....dddd....",
        "............",
        "............",
    ], {"y": "#E8C170", "Y": "#C99A45", "d": "#8D6E3F"}),
    "frango": ([
        "..........w.",
        ".........wWw",
        "........wWw.",
        ".......bw...",
        ".....bbbb...",
        "...bbBbbb...",
        "..bBbbbbb...",
        "..bbbbbBb...",
        "..bbbbbb....",
        "...bBbb.....",
        "....bb......",
        "............",
    ], {"b": "#C8783C", "B": "#9A5523", "w": "#F5F5F5", "W": "#C8C8C8"}),
    "bife": ([
        "............",
        "...dddd.....",
        "..dbbbbdd...",
        ".dbbwbbbbd..",
        ".dbbbbwbbbd.",
        ".dbwbbbbbbd.",
        "..dbbbbwbbd.",
        "...dbbbbbbd.",
        "....ddbbbbd.",
        "......dddd..",
        "............",
        "............",
    ], {"b": "#8D4E2A", "d": "#5A2E15", "w": "#E7B98F"}),
    "ensopado": ([
        "............",
        "............",
        "...R....R...",
        ".ssRssssRss.",
        ".sssssRssss.",
        ".wbbbbbbbbw.",
        ".wbbbbbbbbw.",
        "..wbbbbbbw..",
        "...wbbbbw...",
        "....wwww....",
        "............",
        "............",
    ], {"s": "#B5651D", "R": "#D84315", "b": "#8D6E63", "w": "#5D4037"}),
    "cookie": ([
        "............",
        "...cccccc...",
        "..cCcckcCc..",
        ".cckcccccCc.",
        ".cccccCckcc.",
        ".cCcccccccc.",
        ".cckccCcckc.",
        ".ccccckcccc.",
        "..cCcccccc..",
        "...cccccc...",
        "............",
        "............",
    ], {"c": "#D9A066", "C": "#B9803F", "k": "#4E2A12"}),
    "torta": ([
        "............",
        "............",
        "............",
        "...oOoOoO...",
        "..oOOOOOOo..",
        ".oOoOOOoOOo.",
        ".yYYYYYYYYy.",
        ".yyyyyyyyyy.",
        "..yyyyyyyy..",
        "............",
        "............",
        "............",
    ], {"o": "#E07A1F", "O": "#C9631A", "y": "#E8C27A", "Y": "#C9A055"}),
    "bolo": ([
        "............",
        "............",
        "..r..r..r...",
        ".wwwwwwwwww.",
        ".wwwrwwwwrw.",
        ".wwwwwwwwww.",
        ".WwWwWWwWwW.",
        ".bbbbbbbbbb.",
        ".bBbbBbbBbb.",
        ".bbbbbbbbbb.",
        ".BBBBBBBBBB.",
        "............",
    ], {"w": "#FAFAFA", "W": "#D8D8D8", "r": "#E53935", "b": "#C68B59", "B": "#8D5A2B"}),
    "carne_podre": ([
        "............",
        "...ggrr.....",
        "..grrgrrr...",
        ".grrrrgrrg..",
        ".rgrrrrrgrr.",
        ".rrrgrrrrrg.",
        "..grrrgrrrr.",
        "...rrrrgrr..",
        "....grrrr...",
        ".....rgg....",
        "............",
        "............",
    ], {"r": "#A1574A", "g": "#6B8E23"}),
    # ---- bebidas ----
    "agua": (_BOTTLE, {"c": "#8D6E63", "w": "#CFD8DC", "L": "#3F76E4", "h": "#9EC1FF", "D": "#2A55B0"}),
    "pocao_velocidade": (_BOTTLE, {"c": "#8D6E63", "w": "#CFD8DC", "L": "#7CC7E8", "h": "#E1F5FE", "D": "#4FA3C7"}),
    "leite": ([
        "............",
        "...gggggg...",
        "..g......g..",
        ".gwwwwwwwwg.",
        ".gwwwwwwwwg.",
        ".ggwwwwwwgg.",
        "..gGGGGGGg..",
        "..gGgGGGGg..",
        "..gGGGGGGg..",
        "...gGGGGg...",
        "...gggggg...",
        "............",
    ], {"g": "#8A8A8A", "G": "#BDBDBD", "w": "#FFFFFF"}),
    "suco": ([
        "............",
        "..wwwwwwww..",
        "..w......w..",
        "..wrrrrrrw..",
        "..wrhrrrrw..",
        "..wrrrrrrw..",
        "..wrrrrrrw..",
        "..wrrrrRrw..",
        "...wrrrrw...",
        "...wwwwww...",
        "............",
        "............",
    ], {"w": "#CFD8DC", "r": "#EF5350", "R": "#C62828", "h": "#FFCDD2"}),
    "cafe": ([
        "............",
        ".....s.s....",
        "....s.s.....",
        "..wwwwwww...",
        "..wkkkkkwww.",
        "..wwwwwww.w.",
        "..wwwwwww.w.",
        "..wwwwwwwww.",
        "..wwwwwww...",
        "...wwwww....",
        "............",
        "............",
    ], {"w": "#ECEFF1", "k": "#4E342E", "s": "#B0BEC5"}),
    # ---- atividades ----
    "caminhar": ([
        "............",
        "...bbbb.....",
        "...bBbb.....",
        "...bbbb.....",
        "...bBbb.....",
        "...bbbbbb...",
        "...bbbbbbb..",
        "...bbbbbbbb.",
        "...BBBBBBBB.",
        "............",
        "............",
        "............",
    ], {"b": "#A1887F", "B": "#5D4037"}),
    "correr": ([
        "............",
        "...ww.......",
        "..wwwwww....",
        ".....wwwww..",
        "..wwwwwwwww.",
        "......wwwww.",
        "...wwwwwwww.",
        "........www.",
        "..wwwwwww...",
        "............",
        "............",
        "............",
    ], {"w": "#E0F7FA"}),
    "pular": ([
        "............",
        "....gggg....",
        "..gGGGGGgg..",
        ".gGhhGGGGGg.",
        ".gGhGGGGGGg.",
        ".gGGGGGGGGg.",
        ".gGGGGGGgGg.",
        "..gGGGGGGg..",
        "...gggggg...",
        "............",
        "............",
        "............",
    ], {"g": "#4CAF50", "G": "#7BD36E", "h": "#C8F5C0"}),
    "flexao": ([
        "............",
        "............",
        ".kk......kk.",
        ".kk......kk.",
        "kkk......kkk",
        "kkkggggggkkk",
        "kkk......kkk",
        ".kk......kk.",
        ".kk......kk.",
        "............",
        "............",
        "............",
    ], {"k": "#424242", "g": "#9E9E9E"}),
    "dancar": ([
        "....kkkk....",
        "..kkkkkkkk..",
        ".kkkKkkkkkk.",
        ".kkKkrrkkkk.",
        "kkkkryyrkkkk",
        "kkkryyyyrkkk",
        "kkkryyyyrkkk",
        "kkkkryyrkkkk",
        ".kkkkrrkkKk.",
        ".kkkkkkkKkk.",
        "..kkkkkkkk..",
        "....kkkk....",
    ], {"k": "#212121", "K": "#616161", "r": "#E53935", "y": "#FFEB3B"}),
    "descansar": ([
        "............",
        "............",
        "............",
        "..pppppppp..",
        "..pPPPPPPp..",
        "..pppppppp..",
        "..bbbbbbbb..",
        "..b......b..",
        "..b......b..",
        "..b......b..",
        "............",
        "............",
    ], {"p": "#B39DDB", "P": "#9575CD", "b": "#795548"}),
    "gato": ([
        "............",
        ".o.......o..",
        ".oo.....oo..",
        ".ooooooooo..",
        ".oOoooooOo..",
        ".okgoooogk..",
        ".ooooooooo..",
        ".oooopoooo..",
        "..owwwwwo...",
        "...ooooo....",
        "............",
        "............",
    ], {"o": "#F2B04E", "O": "#E08A1E", "k": "#212121", "g": "#7CB342", "p": "#F48FB1", "w": "#FFF3E0"}),
    # ---- botões / ações ----
    "dormir": ([
        "............",
        "............",
        "............",
        "............",
        "w...........",
        "wwwrrrrrrrr.",
        "wwwrrrrrrrr.",
        "bbbbbbbbbbbb",
        "b..........b",
        "b..........b",
        "............",
        "............",
    ], {"w": "#FAFAFA", "r": "#D32F2F", "b": "#6D4C41"}),
    "acordar": ([
        "............",
        ".....y......",
        "..y..y..y...",
        "...yyyyy....",
        "..yyyyyyy...",
        "yyyyyyyyyyy.",
        "..yyyyyyy...",
        "...yyyyy....",
        "..y..y..y...",
        ".....y......",
        "............",
        "............",
    ], {"y": "#FFC107"}),
    "carinho": ([
        "............",
        "............",
        "..rr...rr...",
        ".rhrr.rrrr..",
        ".rhrrrrrrR..",
        ".rrrrrrrrR..",
        "..rrrrrrR...",
        "...rrrrR....",
        "....rrR.....",
        ".....R......",
        "............",
        "............",
    ], {"r": "#E53935", "R": "#B71C1C", "h": "#FFCDD2"}),
    "bandeja": ([
        "............",
        ".....ww.....",
        ".....ww.....",
        ".....ww.....",
        "...wwwwww...",
        "....wwww....",
        ".....ww.....",
        ".g........g.",
        ".g........g.",
        ".gggggggggg.",
        "............",
        "............",
    ], {"w": "#FFFFFF", "g": "#CFD8DC"}),
    "menu": ([
        "............",
        "............",
        "..wwwwwwww..",
        "..wwwwwwww..",
        "............",
        "..wwwwwwww..",
        "..wwwwwwww..",
        "............",
        "..wwwwwwww..",
        "..wwwwwwww..",
        "............",
        "............",
    ], {"w": "#FFFFFF"}),
    "comer": ([
        "............",
        "........ww..",
        ".......wWw..",
        "......bwW...",
        ".....bbb....",
        "...bbBbb....",
        "..bBbbbb....",
        "..bbbbBb....",
        "..bbbbb.....",
        "...bbb......",
        "............",
        "............",
    ], {"b": "#C8783C", "B": "#9A5523", "w": "#F5F5F5", "W": "#C8C8C8"}),
    "beber": (_BOTTLE, {"c": "#8D6E63", "w": "#CFD8DC", "L": "#3F76E4", "h": "#9EC1FF", "D": "#2A55B0"}),
    "atividades": ([
        "............",
        "...gggg.....",
        ".gGGGGGgg...",
        "gGhhGGGGGg..",
        "gGhGGGGGGg..",
        "gGGGGGGGGg..",
        ".gGGGGGGg...",
        "..gggggg....",
        "............",
        "............",
        "............",
        "............",
    ], {"g": "#4CAF50", "G": "#7BD36E", "h": "#C8F5C0"}),
    # ---- progresso ----
    "presente": ([
        "..yy....yy..",
        "..yYy..yYy..",
        "...yYyyYy...",
        "lllllyylllll",
        "LLLLLyyLLLLL",
        ".rrrryyrrrR.",
        ".rhrryyrrrR.",
        ".rrrryyrrrR.",
        ".rrrryyrrrR.",
        ".rrrryyrrrR.",
        ".RRRRYYRRRR.",
        "............",
    ], {"y": "#FFD54F", "Y": "#C79100", "l": "#EF5350", "L": "#B71C1C", "r": "#E53935", "R": "#8E1B1B",
        "h": "#FF8A80"}),
    "polvora": ([
        "............",
        "............",
        "............",
        ".....gg.....",
        "....gGgg....",
        "...gGgDgg...",
        "..gGggDgGg..",
        ".gGgDggGgDg.",
        ".gggGgDgggg.",
        "gDggGggDggGg",
        "gggggggggggg",
        "............",
    ], {"g": "#757575", "G": "#9E9E9E", "D": "#424242"}),
    "relogio": ([
        "............",
        "....yyyy....",
        "..yyWWWWyy..",
        ".yWWWWWWWWy.",
        ".yWWWbWWWWy.",
        "yWWWWbWWWWWy",
        "yWWWWbbbWWWy",
        "yWWWWWWWWWWy",
        ".yWWWWWWWWy.",
        ".yyWWWWWWyy.",
        "...yyyyyy...",
        "............",
    ], {"y": "#FFC107", "W": "#FFF8E1", "b": "#424242"}),
    "xp": ([
        "............",
        "............",
        "....gggg....",
        "...gGGGGg...",
        "..gGhhGGGg..",
        "..gGhGGGGg..",
        "..gGGGGGGg..",
        "..gGGGGGDg..",
        "...gGGGDg...",
        "....gggg....",
        "............",
        "............",
    ], {"g": "#4E8A12", "G": "#B5F23A", "h": "#F4FFC2", "D": "#7FD321"}),
    # ---- comidas e bebidas desbloqueáveis ----
    "baga_doce": ([
        "............",
        "....gg......",
        "...gGGg.....",
        "....gg.r....",
        "..rr..rRr...",
        ".rRhr.rrr...",
        ".rrrr..r.rr.",
        "..rr...rrRhr",
        ".....rr.rrrr",
        "....rRhr.rr.",
        "....rrrr....",
        ".....rr.....",
    ], {"r": "#C62828", "R": "#8E1B1B", "h": "#FF8A80", "g": "#43A047", "G": "#2E7D32"}),
    "melancia": ([
        "............",
        "............",
        "............",
        "rrrrrrrrrrrr",
        "rrbrrrrrbrrr",
        ".rrrrbrrrrr.",
        ".wrrrrrrrrw.",
        "..wrrbrrrw..",
        "..GwwwwwwG..",
        "...GGGGGG...",
        "............",
        "............",
    ], {"r": "#E53935", "b": "#212121", "w": "#C5E1A5", "G": "#2E7D32"}),
    "peixe": ([
        "............",
        "............",
        "............",
        "....dddd....",
        "..ddOOOOd.dd",
        ".dOeOOOOOddO",
        "dOOOOOOOOOd.",
        ".dOOOOOOOddO",
        "..ddOOOOd.dd",
        "....dddd....",
        "............",
        "............",
    ], {"d": "#8D4E2A", "O": "#D9893F", "e": "#1A1A1A"}),
    "mel": (_BOTTLE, {"c": "#8D6E63", "w": "#CFD8DC", "L": "#FFB300", "h": "#FFE082", "D": "#C77C00"}),
    "pocao_salto": (_BOTTLE, {"c": "#8D6E63", "w": "#CFD8DC", "L": "#7CFC5A", "h": "#D4FFC4", "D": "#3FA52A"}),
    "pocao_encolher": (_BOTTLE, {"c": "#8D6E63", "w": "#CFD8DC", "L": "#B388FF", "h": "#EDE7F6", "D": "#7E57C2"}),
    "pocao_invisibilidade": (_BOTTLE, {"c": "#8D6E63", "w": "#CFD8DC", "L": "#9EA3B0", "h": "#E8EAF0",
                                       "D": "#6B7080"}),
    "pocao_cura": (_BOTTLE, {"c": "#8D6E63", "w": "#CFD8DC", "L": "#F44369", "h": "#FFC1CF", "D": "#B0103A"}),
    # ---- atividades desbloqueáveis ----
    "minerar": ([
        "....HHHH....",
        ".....SHHHH..",
        ".........HH.",
        "........bSH.",
        ".......b..HH",
        "......b...SH",
        ".....B....H.",
        "....b.......",
        "...B........",
        "..b.........",
        ".B..........",
        "............",
    ], {"H": "#CFD8DC", "S": "#78909C", "b": "#A1887F", "B": "#5D4037"}),
    "pescar": ([
        "..........b.",
        ".........b.w",
        "........b..w",
        ".......b...w",
        "......b....w",
        ".....b.....w",
        "....B......w",
        "...b.......r",
        "..b........R",
        ".B..........",
        "B...........",
        "............",
    ], {"b": "#A1887F", "B": "#5D4037", "w": "#E0E0E0", "r": "#E53935", "R": "#FAFAFA"}),
    "plantar": ([
        "............",
        ".....gg.....",
        "...ggGgg....",
        "..gGggGgg...",
        "...ggGGg.g..",
        ".g..gGgggg..",
        ".gg..bg.....",
        "..g..b......",
        ".....b......",
        "...ddbdd....",
        "..dDddDdd...",
        "............",
    ], {"g": "#66BB6A", "G": "#2E7D32", "b": "#6D4C41", "d": "#795548", "D": "#4E342E"}),
    "porco": ([
        "............",
        "............",
        ".pppppppppp.",
        ".pppppppppp.",
        ".pwkppppkwp.",
        ".pppppppppp.",
        ".pppSSSSppp.",
        ".pppnSSnppp.",
        ".pppppppppp.",
        ".PPPPPPPPPP.",
        "............",
        "............",
    ], {"p": "#F0A5A2", "P": "#D98583", "S": "#F7C1BF", "n": "#8B3A3A", "w": "#FFFFFF", "k": "#1A1A1A"}),
    "fogos": ([
        "......r.....",
        ".....rRr....",
        ".....wWw....",
        ".....rRr....",
        ".....wWw....",
        ".....rRr....",
        ".....rRr....",
        "......b.....",
        "......b.....",
        "......b.....",
        ".....y.y....",
        "....y...y...",
    ], {"r": "#E53935", "R": "#B71C1C", "w": "#FAFAFA", "W": "#E0E0E0", "b": "#8D6E63", "y": "#FFB300"}),
    # ---- coisas que aparecem nas atividades ----
    "vara": ([   # a vara na mão dele, sem linha (a linha de verdade é desenhada até a boia)
        "..........b.",
        ".........b..",
        "........b...",
        ".......b....",
        "......b.....",
        ".....b......",
        "....B.......",
        "...b........",
        "..b.........",
        ".B..........",
        "B...........",
        "............",
    ], {"b": "#A1887F", "B": "#5D4037"}),
    "flor": ([
        "............",
        "...rr.rr....",
        "..rRRrRRr...",
        "..rRyyRRr...",
        "...rRRRr....",
        "....rgr.....",
        "..g..g......",
        "..gg.g.gg...",
        "...ggg.g....",
        ".....gg.....",
        "...ddddd....",
        "..dDddDdd...",
    ], {"r": "#E53935", "R": "#B71C1C", "y": "#212121", "g": "#43A047", "d": "#795548", "D": "#4E342E"}),
    "diamante": ([
        "............",
        "............",
        "...cccccc...",
        "..cCCwCCCc..",
        ".cCwwCCCCCc.",
        ".cCCCCCCCCc.",
        "..cCCCCCCc..",
        "...cCCCCc...",
        "....cCCc....",
        ".....cc.....",
        "............",
        "............",
    ], {"c": "#1E9C8C", "C": "#4AEDD9", "w": "#E0FFFA"}),
    "bota": ([
        "............",
        "...bbbb.....",
        "...bBBb.....",
        "...bBBb.....",
        "...bBBb.....",
        "...bBBbb....",
        "...bBBBBbb..",
        "..bBBBBBBBb.",
        "..bBBBBBBBb.",
        "..bbbbbbbbb.",
        "............",
        "............",
    ], {"b": "#4E342E", "B": "#795548"}),
}

# Guarda-roupa: rastros e creeper carregado
ICONS["folha"] = ([
    "............",
    "........gg..",
    "......gGGg..",
    ".....gGgGg..",
    "....gGgGg...",
    "...gGgGg....",
    "..gGgGg.....",
    "..gGGg......",
    "..bgg.......",
    ".b..........",
    "b...........",
    "............",
], {"g": "#7CB342", "G": "#558B2F", "b": "#6D4C41"})
ICONS["faisca"] = ([
    "............",
    ".....y......",
    ".....y......",
    "....yWy.....",
    "..yyWWWyy...",
    "....yWy.....",
    ".....y......",
    ".....y...y..",
    "........yWy.",
    ".y.......y..",
    "yWy.........",
    ".y..........",
], {"y": "#FFD54F", "W": "#FFFDE7"})
ICONS["raio"] = ([
    ".......bbb..",
    "......bbB...",
    ".....bbB....",
    "....bbB.....",
    "...bbbbbbb..",
    "......bbB...",
    ".....bbB....",
    "....bbB.....",
    "...bB.......",
    "..bB........",
    ".b..........",
    "............",
], {"b": "#4FC3F7", "B": "#E1F5FE"})

# Variações de desenhos que já existem
ICONS["sopa_beterraba"] = (ICONS["ensopado"][0], {"s": "#B71C1C", "R": "#E57373", "b": "#8D6E63", "w": "#5D4037"})
ICONS["cenoura_dourada"] = (ICONS["cenoura"][0], {"o": "#FFCA28", "O": "#C79100", "g": "#FFE082", "G": "#FFB300"})

_LUMP = [
    "............",
    "............",
    "............",
    "....LLL.....",
    "..LLlLLL....",
    ".LlLLLLLL...",
    ".LLLLLDLLL..",
    "..LLLDDLLL..",
    "...LLLLLD...",
    ".....DD.....",
    "............",
    "............",
]
ICONS["carvao"] = (_LUMP, {"L": "#2E2E2E", "l": "#5A5A5A", "D": "#151515"})
ICONS["ferro"] = (_LUMP, {"L": "#D8AF93", "l": "#F2D6C2", "D": "#9C7A63"})

# Blocos de minério: textura de pedra com manchas do minério por cima.
_STONE_RNG = random.Random(7)
_STONE = ["".join(_STONE_RNG.choice("sssSSd") for _ in range(12)) for _ in range(12)]
_ORE = [
    "............",
    ".oo.........",
    ".oOo....oo..",
    "..o....oOO..",
    "........o...",
    "....oo......",
    "...oOOo.....",
    "....oo...oo.",
    ".........oOo",
    ".oo......o..",
    ".oOo........",
    "............",
]
_STONE_COLORS = {"s": "#8E8E8E", "S": "#A5A5A5", "d": "#6E6E6E"}


def _ore_block(ore: str | None, light: str = "", dark: str = "") -> tuple[list[str], dict[str, str]]:
    if ore is None:
        return _STONE, _STONE_COLORS
    grid = ["".join(o if o != "." else s for s, o in zip(srow, orow)) for srow, orow in zip(_STONE, _ORE)]
    return grid, {**_STONE_COLORS, "o": light, "O": dark}


ICONS["bloco_pedra"] = _ore_block(None)
ICONS["bloco_carvao"] = _ore_block("carvao", "#2B2B2B", "#454545")
ICONS["bloco_ferro"] = _ore_block("ferro", "#D8AF93", "#AF8E77")
ICONS["bloco_diamante"] = _ore_block("diamante", "#4AEDD9", "#A1FBE8")

# Desenhos maiores que 12x12 (tamanho livre).
BIG: dict[str, tuple[list[str], dict[str, str]]] = {}
_PIG_TOP = [
    "...........ppppp",
    ".PPPPPPPPPPpwkpp",
    "ppppppppppppppps",
    "pppppppppppppppn",
    "ppppppppppppppps",
    "ppppppppppppppp.",
    ".pppppppppppppp.",
    ".PP.PP...PP.PP..",
]
_PIG_COLORS = {"p": "#F0A5A2", "P": "#D98583", "w": "#FFFFFF", "k": "#1A1A1A", "s": "#F7C1BF",
               "n": "#8B3A3A", "D": "#6D4C41"}
BIG["porco_1"] = (_PIG_TOP + [".PP.PP...PP.PP..", ".DD.DD...DD.DD.."], _PIG_COLORS)
BIG["porco_2"] = (_PIG_TOP + ["PP...PP.PP...PP.", "DD...DD.DD...DD."], _PIG_COLORS)

# Ícones pequenos (8x8) das barras de status, estilo barra de fome do Minecraft.
STATUS_ICONS: dict[str, tuple[list[str], dict[str, str]]] = {
    "fome": ([
        ".....ww.",
        "....wWw.",
        "...bw...",
        "..bbbb..",
        ".bBbbb..",
        ".bbbBb..",
        ".bbbb...",
        "..bb....",
    ], {"b": "#C8783C", "B": "#9A5523", "w": "#F5F5F5", "W": "#C8C8C8"}),
    "sede": ([
        "...b....",
        "...b....",
        "..bbb...",
        ".bbbbb..",
        ".bhbbb..",
        ".bhbbb..",
        "..bbb...",
        "........",
    ], {"b": "#3F76E4", "h": "#9EC1FF"}),
    "energia": ([
        "....yy..",
        "...yy...",
        "..yy....",
        ".yyyyy..",
        "...yy...",
        "..yy....",
        ".yy.....",
        ".y......",
    ], {"y": "#FFD54F"}),
    "sono": ([
        "..mmm...",
        ".mm.....",
        "mm......",
        "mm......",
        "mm......",
        ".mm...m.",
        "..mmmm..",
        "........",
    ], {"m": "#B3E5FC"}),
    "diversao": ([
        "...y....",
        "...y....",
        "yyyyyyy.",
        ".yyyyy..",
        "..yyy...",
        ".yy.yy..",
        ".y...y..",
        "........",
    ], {"y": "#FFEB3B"}),
}


def names() -> list[str]:
    return list(ICONS)


def _build(grid: list[str], palette: dict[str, str], size: int | None = None, dim: bool = False) -> QImage:
    """Monta a imagem a partir da grade. Sem `size`, usa o tamanho da própria grade."""
    w, h = (size, size) if size else (len(grid[0]), len(grid))
    img = QImage(w, h, QImage.Format_ARGB32_Premultiplied)
    img.fill(Qt.transparent)
    p = QPainter(img)
    colors = {k: QColor(v) for k, v in palette.items()}
    for y, row in enumerate(grid[:h]):
        for x, ch in enumerate(row[:w]):
            color = colors.get(ch)
            if color is None:
                continue
            if dim:
                color = QColor(30, 30, 30, 170)
            p.fillRect(x, y, 1, 1, color)
    p.end()
    return img


@lru_cache(maxsize=None)
def image(name: str) -> QImage:
    grid, palette = ICONS.get(name, ICONS["maca"])
    return _build(grid, palette, 12)


@lru_cache(maxsize=None)
def hat_image(hat_id: str) -> QImage:
    hat = cosmetics.HATS[hat_id]
    return _build(hat["grade"], hat["cores"])


@lru_cache(maxsize=None)
def big_image(name: str) -> QImage:
    grid, palette = BIG[name]
    return _build(grid, palette)


@lru_cache(maxsize=None)
def status_image(stat: str, dim: bool = False) -> QImage:
    grid, palette = STATUS_ICONS[stat]
    return _build(grid, palette, 8, dim)


def pixmap(name: str, scale: int = 2):
    """QPixmap ampliado sem suavização (precisa de QApplication)."""
    from PySide6.QtGui import QPixmap
    img = image(name)
    return QPixmap.fromImage(img.scaled(img.width() * scale, img.height() * scale, Qt.IgnoreAspectRatio, Qt.FastTransformation))
